<?php
// $Id$
define('SERVICES_MOTEVIA_PATH', drupal_get_path('module', 'services_motevia'));

/**
 * @file
 *  Provides a generic but powerful API for web services.
 */

/**
 * Implementation of hook_views_api().
 */
function services_motevia_views_api() {
  return array(
    'api' => 2.0,
	'path' => SERVICES_MOTEVIA_PATH,
  );
}

/**
 * Implements hook_views_data()
 */
function services_motevia_views_data() {

  // Define the base group of this table. Fields that don't
  // have a group defined will go into this field by default.
  $data['node_type']['table']['group']  = t('Node Type');

  // Advertise this table as a possible base table
  $data['node_type']['table']['base'] = array(
    'field' => 'type',
    'title' => t('Node Type'),
    'help' => t("Node Types."),
  );

  // ----------------------------------------------------------------
  // Fields

  // title
  $data['node_type']['type'] = array(
    'title' => t('type'), // The item it appears as on the UI,
    'help' => t('The type of the node.'),
     // Information for displaying a title as a field
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
     ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    // Information for accepting a title as a filter
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
  );

    // name
  $data['node_type']['name'] = array(
    'title' => t('name'), // The item it appears as on the UI,
    'help' => t('The name of the type.'),
     // Information for displaying a title as a field
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
     ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    // Information for accepting a title as a filter
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
  );
  
 
  // feed body
  $data['node_type']['description'] = array(
    'title' => t('Body'), // The item it appears as on the UI,
    'help' => t('The actual content of the imported item.'),
     // Information for displaying a title as a field
    'field' => array(
      'handler' => 'views_handler_field_aggregator_xss',
      'click sortable' => FALSE,
     ),
    // Information for accepting a title as a filter
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
  );

 
  return $data;
}